name: IAC - network/vpc

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/valdemarceccon/iac-tooling:latest
    steps:
      - uses: actions/checkout@v3

      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        working-directory: network/vpc
        run: terragrunt plan -out tfplan

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: tfplan
          path: network/vpc/tfplan
  apply:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: plan
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/valdemarceccon/iac-tooling:latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3.0.2
        with:
          name: tfplan
          path: network/vpc/tfplan
          
      - name: Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        working-directory: network/vpc
        run: terragrunt apply tfplan
    
