name: IAC - network/vpc

on:
  push:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/valdemarceccon/iac-tooling:latest
      
    steps:
      - uses: actions/checkout@v3

      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        working-directory: network/vpc
        run: terragrunt plan

